package com.ljs.gameserver.mapper;

import com.ljs.gameserver.entry.PlayerCommanderEntry;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface PlayerCommanderEntryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_commanders
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("ownerId") String ownerId, @Param("commanderId") Integer commanderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_commanders
     *
     * @mbg.generated
     */
    int insert(PlayerCommanderEntry record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_commanders
     *
     * @mbg.generated
     */
    PlayerCommanderEntry selectByPrimaryKey(@Param("ownerId") String ownerId, @Param("commanderId") Integer commanderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_commanders
     *
     * @mbg.generated
     */
    List<PlayerCommanderEntry> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table player_commanders
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PlayerCommanderEntry record);
}