package com.ljs.gameserver.entry;

import java.util.Date;

public class PlayerCommanderEntry {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_commanders.owner_id
     *
     * @mbg.generated
     */
    private String ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_commanders.commander_id
     *
     * @mbg.generated
     */
    private Integer commanderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_commanders.level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_commanders.exp
     *
     * @mbg.generated
     */
    private Integer exp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_commanders.power
     *
     * @mbg.generated
     */
    private Integer power;

    private SkillInfo skillInfo;
    private TelentInfo talentInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_commanders.marching_info
     *
     * @mbg.generated
     */
    private String marchingInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_commanders.hurt_times
     *
     * @mbg.generated
     */
    private Integer hurtTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column player_commanders.recover_time
     *
     * @mbg.generated
     */
    private Date recoverTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_commanders.owner_id
     *
     * @return the value of player_commanders.owner_id
     *
     * @mbg.generated
     */
    public String getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_commanders.owner_id
     *
     * @param ownerId the value for player_commanders.owner_id
     *
     * @mbg.generated
     */
    public void setOwnerId(String ownerId) {
        this.ownerId = ownerId == null ? null : ownerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_commanders.commander_id
     *
     * @return the value of player_commanders.commander_id
     *
     * @mbg.generated
     */
    public Integer getCommanderId() {
        return commanderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_commanders.commander_id
     *
     * @param commanderId the value for player_commanders.commander_id
     *
     * @mbg.generated
     */
    public void setCommanderId(Integer commanderId) {
        this.commanderId = commanderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_commanders.level
     *
     * @return the value of player_commanders.level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_commanders.level
     *
     * @param level the value for player_commanders.level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_commanders.exp
     *
     * @return the value of player_commanders.exp
     *
     * @mbg.generated
     */
    public Integer getExp() {
        return exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_commanders.exp
     *
     * @param exp the value for player_commanders.exp
     *
     * @mbg.generated
     */
    public void setExp(Integer exp) {
        this.exp = exp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_commanders.power
     *
     * @return the value of player_commanders.power
     *
     * @mbg.generated
     */
    public Integer getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_commanders.power
     *
     * @param power the value for player_commanders.power
     *
     * @mbg.generated
     */
    public void setPower(Integer power) {
        this.power = power;
    }

    public SkillInfo getSkillInfo() {
        return skillInfo;
    }


    public void setSkillInfo(SkillInfo skillInfo) {
        this.skillInfo = skillInfo ;
    }


    public TelentInfo getTalentInfo() {
        return talentInfo;
    }


    public void setTalentInfo(TelentInfo talentInfo) {
        this.talentInfo = talentInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_commanders.marching_info
     *
     * @return the value of player_commanders.marching_info
     *
     * @mbg.generated
     */
    public String getMarchingInfo() {
        return marchingInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_commanders.marching_info
     *
     * @param marchingInfo the value for player_commanders.marching_info
     *
     * @mbg.generated
     */
    public void setMarchingInfo(String marchingInfo) {
        this.marchingInfo = marchingInfo == null ? null : marchingInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_commanders.hurt_times
     *
     * @return the value of player_commanders.hurt_times
     *
     * @mbg.generated
     */
    public Integer getHurtTimes() {
        return hurtTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_commanders.hurt_times
     *
     * @param hurtTimes the value for player_commanders.hurt_times
     *
     * @mbg.generated
     */
    public void setHurtTimes(Integer hurtTimes) {
        this.hurtTimes = hurtTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column player_commanders.recover_time
     *
     * @return the value of player_commanders.recover_time
     *
     * @mbg.generated
     */
    public Date getRecoverTime() {
        return recoverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column player_commanders.recover_time
     *
     * @param recoverTime the value for player_commanders.recover_time
     *
     * @mbg.generated
     */
    public void setRecoverTime(Date recoverTime) {
        this.recoverTime = recoverTime;
    }
}